spring:

  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://koa-database.cuoqpzaevx20.ap-northeast-2.rds.amazonaws.com:3306/koa_database
    username: koadatabase
    password: koadatabase

  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
        show_sql: true

# swagger settings
springdoc:
  swagger-ui:
    path: /api-docs
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha # 정렬 기준
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**

logging:
  level:
    org:
      hibernate.sql: debug